# This file contains the default parameter configurations that yield the
# figures present in the final version of the paper

DISABLE_DOER: False # if True, bypasses Doer functionality altogether. No calculation will be loaded or saved
DOER_DIR: 'default'

DISABLE_STORE: False # if True, disables store functionality. No operator will be loaded or saved
STORE_DIR: 'default'

SHOW_FIGURES: False # show figures at runtime
SAVE_FIGURES: True
FIG_DIR: 'default' # where to store figures
FIGURES_USETEX: False # whether LaTeX will be used to render fonts in figures. See: https://matplotlib.org/stable/users/explain/text/usetex.html

# ---- General calculation parameters  ----
N_qu: 2048 # Hilbert space dimension
N_qu_alt: 256 # used in Fig. S4

n_final: 20 # final time step

q0p0: [0.2, 0.3] # center of Gaussian density
s: 0.45 # standard deviation of Gaussian density
q0p0_alt: [0.4, 0.5] # used in Fig. S4
s_alt: 0.1 # used in Fig. S1 (left) and Fig. S4

# Parameters for cat maps
ks_cats: [0.02, 0.025, 0.0275] # perturbation parameters for cat maps
a1s_cats: [0.526, 0.698, 0.822] # corresponding RPRs from https://doi.org/10.1103/PhysRevLett.121.210601
# NOTE: there may be a typo: k values reported in Fig. 1 therein are missing a zero
lyap_cat: 0.96242365 # log((3+5^0.5)/2) for k=0

# Parameters for Harper and standard maps
ks_har_std: [0.94, 19.74] # chaos parameters for Harper and Standard maps
a1s_har_std: [0.38, 0.47] # corresponding RPRs from https://doi.org/10.1103/PhysRevLett.121.210601
lyaps_har_std: [2.3234, 2.3751] # corresponding Lyapunovs for Harper and Standard maps. See: ../auxiliary/calculate_lyapunovs.py
